name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/941847389917/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-deployer@abhishek-angad-reporters-desk1.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/reportersdesk-repo/cms:latest .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/reportersdesk-repo/cms:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: reportersdesk-cms
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/reportersdesk-repo/cms:latest
          region: us-central1
          env_vars: |
            DATABASE_URI=${{ secrets.DATABASE_URI }}
            PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }}
            PENDING_2FA_SECRET=${{ secrets.PENDING_2FA_SECRET }}
            GCS_BUCKET_NAME=${{ secrets.GCS_BUCKET_NAME }}
            GCS_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            RAZORPAY_WEBHOOK_SECRET=${{ secrets.RAZORPAY_WEBHOOK_SECRET }}
            RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }}
            RAZORPAY_KEY_SECRET=${{ secrets.RAZORPAY_KEY_SECRET }}
            RAZORPAY_PLAN_ID_READER=${{ secrets.RAZORPAY_PLAN_ID_READER }}
            RAZORPAY_PLAN_ID_FOI_PATRON=${{ secrets.RAZORPAY_PLAN_ID_FOI_PATRON }}
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}

